
module  ConstIndex
  # Google
  GOOGLE_STORAGE = 1
  GOOGLE_EMAIL   = 0
  GOOGLE_NEXT_ONE = 2
  GOOGLE_PASS_STORAGE = 0
  GOOGLE_NEXT_TWO = 1
  GOOGLE_NEXT_THREE = 3
  CONNECT_SAVE = 5
  GOOGLE_USER = 2

  # Dropbox
  DROPBOX_STORAGE = 2
  SIGNIN_WITH_GOOGLE = 0

  # Yandex.Disk
  YANDEX_STORAGE = 4

  # Facebook
  FACEBOOK_LOGIN    = 0
  FACEBOOK_PASS     = 1
  FACEBOOK_NEXT     = 0
  FACEBOOK_CONTINUE = 0

  # Personal
  PERSONAL_TAB = 2

  # Onedrive
  ONEDRIVE_STORAGE   = 3
  ONEDRIVE_LOGIN     = 0
  ONEDRIVE_NEXT_ONE  = 0
  ONEDRIVE_PASS      = 0
  ONEDRIVE_NEXT_TWO  = 1


  BACK      = 0
end