# frozen_string_literal: true

# Module for storing constants
module Consts
  DEFAULT_DOCUMENT_NAME = 'Document'
  DEFAULT_SPREADSHEET_NAME = 'Spreadsheet'
  DEFAULT_PRESENTATION_NAME = 'Presentation'
  DEFAULT_FOLDER_NAME = 'Folder'
  DEFAULT_PROJECT_NAME = 'Project'

  PREFIX_ADMIN = 'Admin'
  PREFIX_USER = 'User'

  PREFIX_CREATE = 'Created'

  module MyDocuments
    PREFIX = 'MyDocuments'

    DOCUMENT_NAME = PREFIX + DEFAULT_DOCUMENT_NAME
    SPREADSHEET_NAME = PREFIX + DEFAULT_SPREADSHEET_NAME
    PRESENTATION_NAME = PREFIX + DEFAULT_PRESENTATION_NAME
    FOLDER_NAME = PREFIX + DEFAULT_FOLDER_NAME
  end

  module SharedWithMe
    ADMIN_DOCUMENT_NAME = PREFIX_ADMIN + DEFAULT_DOCUMENT_NAME
    ADMIN_SPREADSHEET_NAME = PREFIX_ADMIN + DEFAULT_SPREADSHEET_NAME
    ADMIN_PRESENTATION_NAME = PREFIX_ADMIN + DEFAULT_PRESENTATION_NAME
    ADMIN_FOLDER_NAME = PREFIX_ADMIN + DEFAULT_FOLDER_NAME

    USER_DOCUMENT_NAME = PREFIX_USER + DEFAULT_DOCUMENT_NAME
    USER_SPREADSHEET_NAME = PREFIX_USER + DEFAULT_SPREADSHEET_NAME
    USER_PRESENTATION_NAME = PREFIX_USER + DEFAULT_PRESENTATION_NAME
    USER_FOLDER_NAME = PREFIX_ADMIN + DEFAULT_FOLDER_NAME
  end

  module CommonDocuments
    PREFIX = 'CommonDocuments'

    DOCUMENT_NAME = PREFIX + DEFAULT_DOCUMENT_NAME
    SPREADSHEET_NAME = PREFIX + DEFAULT_SPREADSHEET_NAME
    PRESENTATION_NAME = PREFIX + DEFAULT_PRESENTATION_NAME
    FOLDER_NAME = PREFIX + DEFAULT_FOLDER_NAME
  end

  module ProjectDocuments
    PREFIX = 'ProjectDocuments'

    DOCUMENT_NAME = PREFIX + DEFAULT_DOCUMENT_NAME
    SPREADSHEET_NAME = PREFIX + DEFAULT_SPREADSHEET_NAME
    PRESENTATION_NAME = PREFIX + DEFAULT_PRESENTATION_NAME
    FOLDER_NAME = PREFIX + DEFAULT_FOLDER_NAME

    ADMIN_PROJECT_NAME = PREFIX_ADMIN + DEFAULT_PROJECT_NAME
    USER_PROJECT_NAME = PREFIX_USER + DEFAULT_PROJECT_NAME
  end

  module TrashDocuments
    PREFIX = 'Trash'

    DOCUMENT_NAME = PREFIX + DEFAULT_DOCUMENT_NAME
    SPREADSHEET_NAME = PREFIX + DEFAULT_SPREADSHEET_NAME
    PRESENTATION_NAME = PREFIX + DEFAULT_PRESENTATION_NAME
    FOLDER_NAME = PREFIX + DEFAULT_FOLDER_NAME
  end
end
